
spring:
  application:
    name: user-service

  datasource:
    driver-class-name: mysql.cj.jdbc.Driver
    url : jdbc:mysql://localhost:3306/reddit
    username : root
    password : pass123

    jpa:
      show-sql : true
      hibernate:
        ddl-auto : create-drop
      properties:
        hibernate:
          dialect : org.hibernate.dialect.MySQL5Dialect

server:
  port: 8081

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8090/eureka/
  instance:
    hostname: localhost
